#!/bin/bash

# Part of BrutusNext

tsc --target ES5 --charset UTF-8 --moduleResolution node --newLine LF --noEmitOnError --outDir ./build --rootDir ./src --sourceMap --sourceRoot ./src --module commonjs ./src/BrutusNext.ts
